name: Bootcamp CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    name: Build and Deploy Spring boot API
    runs-on: ubuntu-latest
    steps:
      - uses: listendev/action@v0.10
        with:
          jwt: ${{ secrets.LSTN_API_KEY }}
          ci: only
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Compile
        run: mvn clean compile

      - name: Unit tests
        run: mvn clean test

#      - name: Run API on H2 database (QA)
#        run: |
#          mvn   clean package
#          java -jar -Dspring.profiles.active=qa  target/bootcamp-1.0.jar & APP_PID=$!
#          sleep 30
#
#      - name: Run E2E tests
#        uses: matt-ball/newman-action@master
#        with:
#          collection: Bootcamp-QA.postman_collection.json
#          environment: QA.postman_environment.json
#
#      - name: Stop API
#        run: kill $APP_PID

      - name: Build the API
        run: mvn clean package

#      - name: Get the date
#        id: date
#        run: echo "::set-output name=date::$(date +'%-m%d%H%M')"

#      - name: Build Docker Image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: false
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring:bootcamp

#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Push to Docker Hub
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          dockerfile: Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bank_api:${{ steps.date.outputs.date }}

